# Generated by Django 4.2.7 on 2023-12-04 16:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True, verbose_name='Имя')),
                ('description', models.TextField(max_length=254, verbose_name='Описание')),
                ('course_cost_full', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Полная стоимость обучения')),
                ('course_per_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ежемесячная стоимость обучения')),
                ('link_course', models.URLField(max_length=254)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'default_related_name': 'courses',
            },
        ),
        migrations.CreateModel(
            name='CourseSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'default_related_name': 'courses_skills',
            },
        ),
        migrations.CreateModel(
            name='CourseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата подписки на курс')),
            ],
            options={
                'verbose_name': 'Курс пользователя',
                'verbose_name_plural': 'Курсы пользователя',
                'default_related_name': 'course_users',
            },
        ),
        migrations.CreateModel(
            name='Direction_training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True, verbose_name='Имя')),
                ('duration_training', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Продолжительность лекции')),
            ],
            options={
                'verbose_name': 'Лекция',
                'verbose_name_plural': 'Лекции',
                'default_related_name': 'lessions',
            },
        ),
        migrations.CreateModel(
            name='LessonUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата завершения лекции')),
            ],
            options={
                'verbose_name': 'Лекция пользователя',
                'verbose_name_plural': 'Лекции пользователя',
                'default_related_name': 'leksion_users',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Имя')),
                ('level', models.TextField(max_length=30, verbose_name='Уровень')),
                ('salary', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Заработная плата')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
                'default_related_name': 'professions',
            },
        ),
        migrations.CreateModel(
            name='ProfessionCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'default_related_name': 'professions_courses',
            },
        ),
        migrations.CreateModel(
            name='ProfessionSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'default_related_name': 'professions_skills',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True, verbose_name='Имя')),
                ('link_ikon', models.URLField(max_length=254)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True, verbose_name='Имя')),
                ('salary', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Стоимость')),
                ('salary_measurement', models.TextField(max_length=30, verbose_name='Единица измерения')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('link_vacancy', models.URLField(max_length=254)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.profession', verbose_name='Профессия')),
                ('recruter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.recruitmentcompany', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='VacancySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.skill')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.vacancy')),
            ],
            options={
                'default_related_name': 'vacancy_skills',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.ManyToManyField(through='professions.VacancySkill', to='professions.skill', verbose_name='Навыки'),
        ),
        migrations.CreateModel(
            name='ProfessionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.profession', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профессия пользователя',
                'verbose_name_plural': 'профессии пользователя',
                'default_related_name': 'profession_users',
            },
        ),
    ]
