# Generated by Django 4.2.7 on 2023-12-07 18:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True, verbose_name='Имя')),
                ('description', models.TextField(max_length=254, verbose_name='Описание')),
                ('course_duration', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Длительность курса')),
                ('course_cost_full', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Полная стоимость обучения')),
                ('course_per_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ежемесячная стоимость обучения')),
                ('link_course', models.URLField(max_length=254)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'default_related_name': 'courses',
            },
        ),
        migrations.CreateModel(
            name='DirectionTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Направление обучения',
                'verbose_name_plural': 'Направления обучения',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Имя')),
                ('level', models.TextField(max_length=30, verbose_name='Уровень')),
                ('salary', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Заработная плата')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
                'default_related_name': 'professions',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True, verbose_name='Имя')),
                ('link_ikon', models.URLField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Имя')),
                ('salary', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Стоимость')),
                ('salary_measurement', models.TextField(max_length=30, verbose_name='Единица измерения')),
                ('date', models.DateField(verbose_name='Дата')),
                ('link_vacancy', models.URLField(max_length=254, unique=True)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.profession', verbose_name='Профессия')),
                ('recruter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.recruitmentcompany', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-date'],
                'default_related_name': 'vacancies',
            },
        ),
        migrations.CreateModel(
            name='VacancySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.skill')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.vacancy')),
            ],
            options={
                'verbose_name': 'Вакансия-Навык',
                'verbose_name_plural': 'Вакансии-Навыки',
                'default_related_name': 'vacancy_skills',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.ManyToManyField(through='professions.VacancySkill', to='professions.skill', verbose_name='Навыки'),
        ),
        migrations.CreateModel(
            name='ProfessionSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.profession')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.skill')),
            ],
            options={
                'verbose_name': 'Профессия-Навык',
                'verbose_name_plural': 'Профессии-Навыки',
                'default_related_name': 'professions_skills',
            },
        ),
        migrations.CreateModel(
            name='ProfessionCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.course')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.profession')),
            ],
            options={
                'verbose_name': 'Профессия-Курс',
                'verbose_name_plural': 'Профессии-Курсы',
                'default_related_name': 'professions_courses',
            },
        ),
        migrations.AddField(
            model_name='profession',
            name='course',
            field=models.ManyToManyField(through='professions.ProfessionCourse', to='professions.course', verbose_name='Курсы'),
        ),
        migrations.AddField(
            model_name='profession',
            name='skills',
            field=models.ManyToManyField(through='professions.ProfessionSkill', to='professions.skill', verbose_name='Навыки'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True, verbose_name='Имя')),
                ('duration_training', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Продолжительность лекции')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Лекция',
                'verbose_name_plural': 'Лекции',
                'default_related_name': 'lessions',
            },
        ),
        migrations.CreateModel(
            name='CourseSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.course')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.skill')),
            ],
            options={
                'verbose_name': 'Курс-Навык',
                'verbose_name_plural': 'Курсы-Навыки',
                'default_related_name': 'courses_skills',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='direction_training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.directiontraining', verbose_name='Направление обучения'),
        ),
        migrations.AddField(
            model_name='course',
            name='skill',
            field=models.ManyToManyField(through='professions.CourseSkill', to='professions.skill', verbose_name='Навыки'),
        ),
        migrations.AddConstraint(
            model_name='vacancyskill',
            constraint=models.UniqueConstraint(fields=('vacancy', 'skill'), name='vacancy_skill'),
        ),
        migrations.AddConstraint(
            model_name='professionskill',
            constraint=models.UniqueConstraint(fields=('profession', 'skill'), name='profession_skill'),
        ),
        migrations.AddConstraint(
            model_name='professioncourse',
            constraint=models.UniqueConstraint(fields=('profession', 'course'), name='profession_course'),
        ),
        migrations.AddConstraint(
            model_name='profession',
            constraint=models.UniqueConstraint(fields=('name', 'level'), name='name_level'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('name', 'course'), name='name_course'),
        ),
        migrations.AddConstraint(
            model_name='courseskill',
            constraint=models.UniqueConstraint(fields=('course', 'skill'), name='course_skill'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('name', 'direction_training'), name='name_direction_training'),
        ),
    ]
