# Generated by Django 4.2.7 on 2023-12-01 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='profession',
            name='course',
            field=models.ManyToManyField(to='professions.course', verbose_name='Курсы'),
        ),
        migrations.AddField(
            model_name='profession',
            name='skills',
            field=models.ManyToManyField(to='professions.skill', verbose_name='Навыки'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='lessionuser',
            name='lession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.lesson', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='lessionuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='courseuser',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.course', verbose_name='Курсы'),
        ),
        migrations.AddField(
            model_name='courseuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='course',
            name='skill',
            field=models.ManyToManyField(to='professions.skill', verbose_name='Навыки'),
        ),
        migrations.AddField(
            model_name='course',
            name='training_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.trainingprogram', verbose_name='Профессия'),
        ),
    ]
