# Generated by Django 4.2.7 on 2023-12-04 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='professionuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='professionskill',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.profession'),
        ),
        migrations.AddField(
            model_name='professionskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.skill'),
        ),
        migrations.AddField(
            model_name='professioncourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.course'),
        ),
        migrations.AddField(
            model_name='professioncourse',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.profession'),
        ),
        migrations.AddField(
            model_name='profession',
            name='course',
            field=models.ManyToManyField(through='professions.ProfessionCourse', to='professions.course', verbose_name='Курсы'),
        ),
        migrations.AddField(
            model_name='profession',
            name='skills',
            field=models.ManyToManyField(through='professions.ProfessionSkill', to='professions.skill', verbose_name='Навыки'),
        ),
        migrations.AddField(
            model_name='lessonuser',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.lesson', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='lessonuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='courseuser',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.course', verbose_name='Курсы'),
        ),
        migrations.AddField(
            model_name='courseuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='courseskill',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.course'),
        ),
        migrations.AddField(
            model_name='courseskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.skill'),
        ),
        migrations.AddField(
            model_name='course',
            name='direction_training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.directiontraining', verbose_name='Профессия'),
        ),
        migrations.AddField(
            model_name='course',
            name='skill',
            field=models.ManyToManyField(through='professions.CourseSkill', to='professions.skill', verbose_name='Навыки'),
        ),
        migrations.AddConstraint(
            model_name='vacancyskill',
            constraint=models.UniqueConstraint(fields=('vacancy', 'skill'), name='vacancy_skill'),
        ),
        migrations.AddConstraint(
            model_name='professionuser',
            constraint=models.UniqueConstraint(fields=('user', 'profession'), name='user_profession'),
        ),
        migrations.AddConstraint(
            model_name='professionskill',
            constraint=models.UniqueConstraint(fields=('profession', 'skill'), name='profession_skill'),
        ),
        migrations.AddConstraint(
            model_name='professioncourse',
            constraint=models.UniqueConstraint(fields=('profession', 'course'), name='profession_course'),
        ),
        migrations.AddConstraint(
            model_name='profession',
            constraint=models.UniqueConstraint(fields=('name', 'level'), name='name_level'),
        ),
        migrations.AddConstraint(
            model_name='lessonuser',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='user_lession'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('name', 'course'), name='name_course'),
        ),
        migrations.AddConstraint(
            model_name='courseuser',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='user_course'),
        ),
        migrations.AddConstraint(
            model_name='courseskill',
            constraint=models.UniqueConstraint(fields=('course', 'skill'), name='course_skill'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('name', 'direction_training'), name='name_direction_training'),
        ),
    ]
