# Generated by Django 4.2.7 on 2023-12-08 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Длительность курса'),
        ),
    ]
