# Generated by Django 4.2.7 on 2023-12-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0002_alter_vacancy_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
