# Generated by Django 4.2.7 on 2023-12-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseuser',
            name='date',
            field=models.DateField(verbose_name='Дата подписки на курс'),
        ),
        migrations.AlterField(
            model_name='lessonuser',
            name='date',
            field=models.DateField(verbose_name='Дата завершения лекции'),
        ),
    ]
